### ISSUE TITLE
Comment  and clean code

### ISSUE THREAD

**Issue by JolieKimy** [HE-Arc/dream-baby#28]
Our code doesn't contain enought comments so we absolutly need to add some.

In the mean time, we can clean the dead code.

* [x] comments
* [x] delete dead code
* [x] respect dry
* [x] eloquent features

**Comment by SergiyGolov** [comment]
+ respect more DRY
+ use features offered by Eloquent

**Comment by JolieKimy** [comment]
After many readings, it's seems to be complete considering the remaining time.
