### ISSUE TITLE
Swipe : display wrong sex

### ISSUE THREAD

**Issue by JolieKimy** [HE-Arc/dream-baby#35]
In the swipe, the sex displayed is wrong. We verify in the DB and the content is valid. In the view swipe, the test seems ok...

**Comment by celiendonze** [comment]
https://github.com/HE-Arc/dream-baby/blob/37d40979e9814fad70a3786ef636a32f32913343/app/Http/Controllers/DonorController.php#L191-L207
@SergiyGolov  ça doit être ici, il semble manquer le sexe dans le remplissage des données
